version: "3.3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - ${PORT}:3306
    expose:
      - ${PORT}
    volumes:
      - ./db:/var/lib/mysql
